version = 5.8.0
archive_dir = /etc/letsencrypt/archive/giriwithdevops.duckdns.org-0001
cert = /etc/letsencrypt/live/giriwithdevops.duckdns.org-0001/cert.pem
privkey = /etc/letsencrypt/live/giriwithdevops.duckdns.org-0001/privkey.pem
chain = /etc/letsencrypt/live/giriwithdevops.duckdns.org-0001/chain.pem
fullchain = /etc/letsencrypt/live/giriwithdevops.duckdns.org-0001/fullchain.pem
[renewalparams]
account = 283fcff9e9ee7a6b8c82247f4708d0d9
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
giriwithdevops.duckdns.org = /var/www/certbot
